use std::collections::BTreeMap;

use std::sync::LazyLock;

use regex::Regex;

use crate::transform_one;

#[derive(Clone, Debug)]
struct FgBgStorage {
    fore: String,
    back: String,
}

type ColorMap = BTreeMap<String, FgBgStorage>;

static NAMED_COLORS: LazyLock<ColorMap> = LazyLock::new(|| {
    let mut m: ColorMap = BTreeMap::new();

    for (k, v) in NAME_RGB_COLORS {
        let fb = FgBgStorage {
            fore: transform_one(v.to_string().as_str()).expect("this is bad 1"),
            back: transform_one(&v.replace("#", "$")).expect("this is bad 2"),
        };

        m.insert(k.to_string(), fb);
    }
    m
});

pub fn get_named_foreground_escape(name: &str) -> Option<&str> {
    match NAMED_COLORS.get(name) {
        Some(s) => Some(&s.fore),
        None => None,
    }
}

pub fn get_named_background_escape(name: &str) -> Option<&str> {
    match NAMED_COLORS.get(name) {
        Some(s) => Some(&s.back),
        None => None,
    }
}

pub fn named_color_iter() -> impl Iterator<Item = &'static (&'static str, &'static str)> {
    NAME_RGB_COLORS.iter()
}

pub fn match_name_iter(name: &str) -> impl Iterator<Item = &'static (&'static str, &'static str)> {
    let re = Regex::new(&format!("(?i){}", name)).unwrap();

    NAME_RGB_COLORS.iter().filter(move |x| re.is_match(x.0))
}

#[rustfmt::skip]
///```
/// use ee_conio_macro::named_color_iter;
/// for (name, code) in named_color_iter()
/// {
///     let n = format!("(\"{name}\",");
///     let c = format!("\"{code}\"),");
///     println!("    {n:<30}  {c:<15}");
/// }
///```
pub static NAME_RGB_COLORS: &[(&str, &str)] = &[
    ("Vantablack",                  "#000100"),
    ("Registration Black",          "#000200"),
    ("Rich Black",                  "#010B13"),
    ("Crow",                        "#0D0907"),
    ("Night",                       "#0C090A"),
    ("Smoky Black",                 "#100C08"),
    ("Black",                       "#000000"),
    ("Vampire Black",               "#080808"),
    ("Chinese Black",               "#141414"),
    ("Eerie Black",                 "#1B1B1B"),
    ("Raisin Black",                "#242124"),
    ("Matte Black",                 "#282828"),
    ("Jet",                         "#343434"),
    ("Onyx",                        "#353839"),
    ("Dark Gray",                   "#3A3B3C"),
    ("Black Olive",                 "#3B3C36"),
    ("Iridium",                     "#3D3C3A"),
    ("Light Black",                 "#454545"),
    ("Black Cow",                   "#4C4646"),
    ("Gray Wolf",                   "#504A4B"),
    ("Dark Liver",                  "#534B4F"),
    ("Traffic Gray B",              "#4E5451"),
    ("Vampire Gray",                "#565051"),
    ("Davy’s Gray",                 "#555555"),
    ("Gray Dolphin",                "#5C5858"),
    ("Carbon Gray",                 "#625D5D"),
    ("Granite Gray",                "#676767"),
    ("Dim Gray",                    "#696969"),
    ("Nardo Gray",                  "#686A6C"),
    ("Cloudy Gray",                 "#6D6968"),
    ("Smokey Gray",                 "#726E6D"),
    ("Alien Gray",                  "#736F6E"),
    ("Nickel",                      "#727472"),
    ("Sonic Silver",                "#757575"),
    ("Platinum Gray",               "#797979"),
    ("Granite",                     "#837E7C"),
    ("Neon Gray",                   "#808080"),
    ("Rocket Metallic",             "#8A7F80"),
    ("Battleship Gray",             "#848482"),
    ("Titanium",                    "#878681"),
    ("Middle Gray",                 "#8B8680"),
    ("Taupe Gray",                  "#8B8589"),
    ("Mummy’s Tomb",                "#828E84"),
    ("Philippine Gray",             "#8C8C8C"),
    ("Gunmetal Gray",               "#8D918D"),
    ("Traffic Gray A",              "#8F9695"),
    ("Spanish Gray",                "#989898"),
    ("Quick Silver",                "#A6A6A6"),
    ("Dark Grey",                   "#A9A9A9"),
    ("Metallic Silver",             "#A8A9AD"),
    ("Silver Chalice",              "#ACACAC"),
    ("Silver Foil",                 "#AFB1AE"),
    ("Philippine Silver",           "#B3B3B3"),
    ("Black Shadows",               "#BFAFB2"),
    ("Gray Cloud",                  "#B6B6B4"),
    ("Ash Gray",                    "#B2BEB5"),
    ("Silver",                      "#C0C0C0"),
    ("Silver Sand",                 "#BFC1C2"),
    ("Pale Silver",                 "#C9C0BB"),
    ("Lavender Gray",               "#C4C3D0"),
    ("Neon Silver",                 "#CCCCCC"),
    ("Pastel Gray",                 "#CFCFC4"),
    ("Platinum Silver",             "#CECECE"),
    ("Languid Lavender",            "#D6CADD"),
    ("Gray Goose",                  "#D1D0CE"),
    ("Light Grey",                  "#D3D3D3"),
    ("Timberwolf",                  "#DBD7D2"),
    ("Pastel Light Blue",           "#D5D6EA"),
    ("Light Silver",                "#D8D8D8"),
    ("Dark White",                  "#E1D9D1"),
    ("Gainsboro",                   "#DCDCDC"),
    ("White Coffee",                "#E6E0D4"),
    ("Lavender Pinocchio",          "#EBDDE2"),
    ("Ash White",                   "#E9E4D4"),
    ("Platinum",                    "#E5E4E2"),
    ("White Chocolate",             "#EDE6D6"),
    ("Petal",                       "#F5E2E2"),
    ("Lavender Mist",               "#E6E6FA"),
    ("Alabaster",                   "#F2F0E6"),
    ("Isabelline",                  "#F4F0EC"),
    ("Off White",                   "#F8F0E3"),
    ("Linen",                       "#FAF0E6"),
    ("Cloud",                       "#EFF1FE"),
    ("White Smoke",                 "#F5F5F5"),
    ("Lavender Blush",              "#FFF0F5"),
    ("Old Lace",                    "#FDF5E6"),
    ("Rice",                        "#FAF5EF"),
    ("Pearl White",                 "#F8F6F0"),
    ("Alice Blue",                  "#F0F8FF"),
    ("Seashell",                    "#FFF5EE"),
    ("Cosmic Latte",                "#FFF8E7"),
    ("Ghost White",                 "#F8F8FF"),
    ("Honeydew",                    "#F0FFF0"),
    ("Traffic White",               "#F7FBF5"),
    ("Zinc White",                  "#FDF8FF"),
    ("Floral White",                "#FFFAF0"),
    ("Cotton",                      "#FBFBF9"),
    ("Mint Cream",                  "#F5FFFA"),
    ("Tooth",                       "#FFFAFA"),
    ("Milk White",                  "#FEFCFF"),
    ("Lotion",                      "#FEFDFA"),
    ("Milk",                        "#FDFFF5"),
    ("Ivory",                       "#FFFFF0"),
    ("Baby Powder",                 "#FEFEFA"),
    ("Light White",                 "#FFFFF7"),
    ("White",                       "#FFFFFF"),
    ("Spicy Mix",                   "#8B5F4D"),
    ("Middle Red Purple",           "#A55353"),
    ("Pastel Brown",                "#836953"),
    ("Mauve Taupe",                 "#915F6D"),
    ("Rose Dust",                   "#9E5E6F"),
    ("Copper Rose",                 "#996666"),
    ("Zircon Gray",                 "#807473"),
    ("Liver Chestnut",              "#987456"),
    ("Dirt",                        "#9B7653"),
    ("Blast-Off Bronze",            "#A57164"),
    ("Copper Penny",                "#AD6F69"),
    ("Tuscan Tan",                  "#A67B5B"),
    ("Burnished Brown",             "#A17A74"),
    ("Cinereous",                   "#98817B"),
    ("Turkish Rose",                "#B57281"),
    ("Beaver",                      "#9F8170"),
    ("Rosy Pink",                   "#B38481"),
    ("Old Rose",                    "#C08081"),
    ("Wild Orchid",                 "#D470A2"),
    ("English Lavender",            "#B48395"),
    ("Pale Violet-Red",             "#DB7093"),
    ("Pink Brown",                  "#C48189"),
    ("Lipstick Pink",               "#C48793"),
    ("New York Pink",               "#D7837F"),
    ("Rosy Brown",                  "#BC8F8F"),
    ("Puce",                        "#CC8899"),
    ("Khaki Rose",                  "#C5908E"),
    ("Pale Taupe",                  "#BC987E"),
    ("Shimmering Blush",            "#D98695"),
    ("Light Coral",                 "#F08080"),
    ("Dusty Pink",                  "#D58A94"),
    ("Antique Brass",               "#CD9575"),
    ("Tuscany",                     "#C09999"),
    ("Middle Red",                  "#E58E73"),
    ("Cadillac Pink",               "#E38AAE"),
    ("Mocha",                       "#BEA493"),
    ("Tulip",                       "#FF878D"),
    ("Dark Salmon",                 "#E9967A"),
    ("Light Thulian Pink",          "#E68FAC"),
    ("Salmon Rose",                 "#E7968B"),
    ("Tickle Me Pink",              "#FC89AC"),
    ("Pink Sherbet",                "#F78FA7"),
    ("Pink Daisy",                  "#E799A3"),
    ("Flamingo",                    "#FC8EAC"),
    ("Salmon Pink",                 "#FF91A4"),
    ("Mauvelous",                   "#EF98AA"),
    ("Silver Pink",                 "#C4AEAD"),
    ("Schauss Pink",                "#FF91AF"),
    ("Tumbleweed",                  "#DEAA88"),
    ("Pastel Pink",                 "#DEA5A4"),
    ("Light Salmon Pink",           "#FF9999"),
    ("Sweet Sixteen",               "#F29EAB"),
    ("Amaranth Pink",               "#F19CBB"),
    ("Pastel Magenta",              "#F49AC2"),
    ("Vivid Tangerine",             "#FFA089"),
    ("Pale Chestnut",               "#DDADAF"),
    ("Metallic Pink",               "#EDA6C4"),
    ("Flamingo Pink",               "#F9A7B0"),
    ("Carnation Pink",              "#FFA6C9"),
    ("Nadeshiko Pink",              "#F6ADC6"),
    ("Donut Pink",                  "#FAAFBE"),
    ("Macaroni And Cheese",         "#FFBD88"),
    ("Cameo Pink",                  "#EFBBCC"),
    ("Light Pink",                  "#FFB6C1"),
    ("Deep Rose",                   "#FBBBB9"),
    ("Cherry Blossom Pink",         "#FFB7C5"),
    ("Melon",                       "#FDBCB4"),
    ("Orchid Pink",                 "#F2BDCD"),
    ("Little Girl Pink",            "#F8B9D4"),
    ("Spanish Pink",                "#F7BFBE"),
    ("Rose Gold",                   "#ECC5C0"),
    ("Desert Sand",                 "#EDC9AF"),
    ("Your Pink",                   "#F4C2C2"),
    ("Cotton Candy",                "#FFBCD9"),
    ("Pink",                        "#FFC0CB"),
    ("Queen Pink",                  "#E8CCD7"),
    ("Deep Peach",                  "#FFCBA4"),
    ("Lotion Pink",                 "#ECCFCF"),
    ("Apricot",                     "#FBCEB1"),
    ("Light Red",                   "#FFCCCB"),
    ("Light Rose",                  "#FBCFCD"),
    ("Peach Puff",                  "#FFDAB9"),
    ("Champagne Pink",              "#F1DDCF"),
    ("Pig Pink",                    "#FDD7E4"),
    ("Pale Pink",                   "#FADADD"),
    ("Unbleached Silk",             "#FFDDCA"),
    ("Mimi Pink",                   "#FFDAE9"),
    ("Piggy Pink",                  "#FDDDE6"),
    ("Pink Bubble Gum",             "#FFDFDD"),
    ("Lumber",                      "#FFE4CD"),
    ("Misty Rose",                  "#FFE4E1"),
    ("Maroon",                      "#800000"),
    ("Dark Red",                    "#8B0000"),
    ("Oxblood",                     "#800020"),
    ("Deep Red",                    "#800517"),
    ("OU Crimson Red",              "#990000"),
    ("Carmine",                     "#960018"),
    ("Purple Maroon",               "#810541"),
    ("Cranberry",                   "#9F000F"),
    ("Falu Red",                    "#801818"),
    ("Medium Red",                  "#B10304"),
    ("Saffron Red",                 "#931314"),
    ("Mordant Red 19",              "#AE0C00"),
    ("Antique Ruby",                "#841B2D"),
    ("Spartan Crimson",             "#9E1316"),
    ("Carbon Red",                  "#A70D2A"),
    ("Smokey Topaz",                "#832A0D"),
    ("Vivid Crimson",               "#CC0033"),
    ("Venetian Red",                "#C80815"),
    ("Rufous",                      "#A81C07"),
    ("Wine Red",                    "#B11226"),
    ("Tomato Sauce",                "#B21807"),
    ("Royal Red",                   "#9B1C31"),
    ("Kobe",                        "#882D17"),
    ("Nintendo Red",                "#E4000F"),
    ("Red Cola",                    "#DF0118"),
    ("Spanish Carmine",             "#D10047"),
    ("Vivid Burgundy",              "#9F1D35"),
    ("Vivid Auburn",                "#922724"),
    ("Traffic Red",                 "#C1121C"),
    ("Rich Carmine",                "#D70040"),
    ("Cadmium Red",                 "#E30022"),
    ("Red Strawberry",              "#EC0304"),
    ("Spanish Red",                 "#E60026"),
    ("Pictorial Carmine",           "#C30B4E"),
    ("Lava",                        "#CF1020"),
    ("Burnt Umber",                 "#8A3324"),
    ("Upsdell Red",                 "#AE2029"),
    ("Big Dip O’Ruby",              "#9C2542"),
    ("Philippine Red",              "#CE1127"),
    ("Medium Candy Apple Red",      "#E2062C"),
    ("Chilli Pepper",               "#C11B17"),
    ("Red",                         "#FF0000"),
    ("Japanese Carmine",            "#9D2933"),
    ("Firebrick",                   "#B22222"),
    ("Stop Red",                    "#CF142B"),
    ("Red-Brown",                   "#A52A2A"),
    ("Iced Tea",                    "#923C01"),
    ("Metallic Red",                "#A62C2B"),
    ("Candy Apple Red",             "#FF0800"),
    ("Solid Pink",                  "#893843"),
    ("Russet",                      "#80461B"),
    ("Fuzzy Wuzzy Brown",           "#87421F"),
    ("Cardinal",                    "#C41E3A"),
    ("Amaranth Purple",             "#AB274F"),
    ("Saddle Brown",                "#8B4513"),
    ("Crimson",                     "#DC143C"),
    ("Vivid Red",                   "#F70D1A"),
    ("Lemon Iced Tea",              "#BD3000"),
    ("Razzmatazz",                  "#E30B5C"),
    ("Raspberry",                   "#E30B5D"),
    ("Fire Engine Red",             "#CE2029"),
    ("Rose Red",                    "#C21E56"),
    ("Cordovan",                    "#893F45"),
    ("Bright Maroon",               "#C32148"),
    ("Love Red",                    "#E41B17"),
    ("Quinacridone Magenta",        "#8E3A59"),
    ("Chinese Red",                 "#AA381E"),
    ("Red Rum",                     "#973A4A"),
    ("Ruby",                        "#E0115F"),
    ("Maximum Red",                 "#D92121"),
    ("Sweet Brown",                 "#A83731"),
    ("Vivid Raspberry",             "#FF006C"),
    ("Burnt Pink",                  "#C12267"),
    ("Tractor Red",                 "#FD0E35"),
    ("Dogwood Rose",                "#D71868"),
    ("Winter Sky",                  "#FF007C"),
    ("Bright Pink",                 "#FF007F"),
    ("Lava Red",                    "#E42217"),
    ("Chestnut",                    "#954535"),
    ("Lust",                        "#E62020"),
    ("Rich Maroon",                 "#B03060"),
    ("Spanish Crimson",             "#E51A4C"),
    ("Pink Violet",                 "#CA226B"),
    ("Metallic Brown",              "#AC4313"),
    ("Neon Red",                    "#FF1818"),
    ("Rogue Pink",                  "#C12869"),
    ("French Raspberry",            "#C72C48"),
    ("Rust",                        "#B7410E"),
    ("Mahogany",                    "#C04000"),
    ("Pale Carmine",                "#AF4035"),
    ("Ruby Red",                    "#F62217"),
    ("Rose Madder",                 "#E32636"),
    ("Persian Red",                 "#CC3333"),
    ("Milk Chocolate",              "#84563C"),
    ("Dingy Dungeon",               "#C53151"),
    ("Madder Lake",                 "#CC3336"),
    ("Scarlet",                     "#FF2400"),
    ("Rusty Red",                   "#DA2C43"),
    ("Neon Scarlet",                "#FF2603"),
    ("Rum",                         "#9A4E40"),
    ("Alizarin",                    "#DB2D43"),
    ("Brown Bear",                  "#835C3B"),
    ("Sinopia",                     "#CB410B"),
    ("Medium Ruby",                 "#AA4069"),
    ("Imperial Red",                "#ED2939"),
    ("Grapefruit",                  "#DC381F"),
    ("Amaranth",                    "#E52B50"),
    ("Watermelon Red",              "#BF4147"),
    ("English Red",                 "#AB4B52"),
    ("Coconut",                     "#965A3E"),
    ("Strawberry Red",              "#C83F49"),
    ("Irresistible",                "#B3446C"),
    ("Pink Lemonade",               "#E4287C"),
    ("Telemagenta",                 "#CF3476"),
    ("Websafe Scarlet",             "#FF3300"),
    ("Cerise",                      "#DE3163"),
    ("Cherry Red",                  "#C24641"),
    ("Chestnut Red",                "#C34A2C"),
    ("Brick Red",                   "#CB4154"),
    ("Fuchsia Purple",              "#CC397B"),
    ("Coquelicot",                  "#FF3800"),
    ("Deep Chestnut",               "#B94E48"),
    ("Burnt Orange",                "#CC5500"),
    ("Redwood",                     "#A45A52"),
    ("English Vermillion",          "#CC474B"),
    ("Hot Deep Pink",               "#F52887"),
    ("Fuchsia Rose",                "#C74375"),
    ("Vermilion",                   "#E34234"),
    ("Red Fox",                     "#C35817"),
    ("Bittersweet Shimmer",         "#BF4F51"),
    ("Paradise Pink",               "#E63E62"),
    ("Light Brown",                 "#B5651D"),
    ("Zarqa",                       "#FF4500"),
    ("Traffic Orange",              "#E15501"),
    ("Alloy Orange",                "#C46210"),
    ("Radical Red",                 "#FF355E"),
    ("Red Salsa",                   "#FD3A4A"),
    ("Xiaomi Orange",               "#FD4900"),
    ("Sizzling Red",                "#FF3855"),
    ("Tangelo",                     "#F94D00"),
    ("Violet Red",                  "#F6358A"),
    ("Dark Gold",                   "#AA6C39"),
    ("Neon Pink",                   "#FE347E"),
    ("Bashful Pink",                "#C25283"),
    ("Microsoft Red",               "#F04E1F"),
    ("Petra Gold",                  "#B76734"),
    ("Cedar Chest",                 "#C95A49"),
    ("Persimmon",                   "#EC5800"),
    ("Flame",                       "#E25822"),
    ("Orioles Orange",              "#FB4F14"),
    ("Metallic Bronze",             "#A97142"),
    ("Tulip Pink",                  "#C25A7C"),
    ("Neon Fuchsia",                "#FE4164"),
    ("Brown Sugar",                 "#AF6E4D"),
    ("Indian Red",                  "#CD5C5C"),
    ("Mystic Red",                  "#FF5500"),
    ("Spanish Orange",              "#E86100"),
    ("Mystic",                      "#D65282"),
    ("Valentine Red",               "#E55451"),
    ("Willpower Orange",            "#FD5800"),
    ("Vivid Red-Tangelo",           "#DF6124"),
    ("Cocoa Brown",                 "#D2691E"),
    ("Metallic Orange",             "#DA680F"),
    ("Medium Vermilion",            "#D9603B"),
    ("Tart Orange",                 "#FB4D46"),
    ("Copper",                      "#B87333"),
    ("Shocking Orange",             "#E55B3C"),
    ("Vivid Vermilion",             "#E56024"),
    ("French Fuchsia",              "#FD3F92"),
    ("Maximum Orange",              "#FF5B00"),
    ("Fandango Pink",               "#DE5285"),
    ("Dark Almond",                 "#AB784E"),
    ("Neon Brown",                  "#C3732A"),
    ("Papaya Orange",               "#E56717"),
    ("Vivid Orange",                "#FF5F00"),
    ("Cinnamon Satin",              "#CD607E"),
    ("Fire Opal",                   "#E95C4B"),
    ("Fuzzy Wuzzy",                 "#CC6666"),
    ("French Rose",                 "#F64A8A"),
    ("Dark Pink",                   "#E75480"),
    ("Copper Red",                  "#CB6D51"),
    ("Orange Soda",                 "#FA5B3D"),
    ("Portland Orange",             "#FF5A36"),
    ("Bright Orange",               "#FF5F1F"),
    ("Blush",                       "#DE5D83"),
    ("Orange Salmon",               "#C47451"),
    ("Orange",                      "#FF6600"),
    ("Orange Iced Tea",             "#FF6700"),
    ("Purple Pink",                 "#D16587"),
    ("Halloween Orange",            "#E66C2C"),
    ("Fiery Rose",                  "#FF5470"),
    ("Bean Red",                    "#F75D59"),
    ("Sunset Orange",               "#FD5E53"),
    ("Watermelon",                  "#F05C85"),
    ("Pink Cupcake",                "#E45E9D"),
    ("Bronze",                      "#CD7F32"),
    ("Light Carmine Pink",          "#E66771"),
    ("Tomato",                      "#FF6347"),
    ("Tiger Orange",                "#C88141"),
    ("Pumpkin Orange",              "#F87217"),
    ("Philippine Orange",           "#FF7300"),
    ("Strawberry Iced Tea",         "#FC5A8D"),
    ("Vivid Tangelo",               "#F07427"),
    ("Terra Cotta",                 "#E2725B"),
    ("Brink Pink",                  "#FB607F"),
    ("Sunrise Orange",              "#E67451"),
    ("Peru",                        "#CD853F"),
    ("Safety Orange",               "#FF7800"),
    ("Medium Orange",               "#FF7802"),
    ("Burnt Sienna",                "#E97451"),
    ("Pumpkin",                     "#FF7518"),
    ("Construction Cone Orange",    "#F87431"),
    ("Heat Wave",                   "#FF7A00"),
    ("Tango Pink",                  "#E4717A"),
    ("Pastel Red",                  "#FF6961"),
    ("Outrageous Orange",           "#FF6E4A"),
    ("Dark Hot Pink",               "#F660AB"),
    ("Thulian Pink",                "#DE6FA1"),
    ("Blush Red",                   "#E56E94"),
    ("Indian Saffron",              "#FF7722"),
    ("Pink Coral",                  "#E77471"),
    ("Light Crimson",               "#F56991"),
    ("Bittersweet",                 "#FE6F5E"),
    ("Mandarin",                    "#F37A48"),
    ("Ultra Red",                   "#FC6C85"),
    ("Raw Sienna",                  "#D68A59"),
    ("Cadmium Orange",              "#ED872D"),
    ("Tiger’s Eye",                 "#E08D3C"),
    ("Cyclamen",                    "#F56FA1"),
    ("French Pink",                 "#FD6C9E"),
    ("Pale Copper",                 "#DA8A67"),
    ("Hot Pink",                    "#FF69B4"),
    ("Medium Pink",                 "#FE6E9F"),
    ("Mango Orange",                "#FF8040"),
    ("Persian Orange",              "#D99058"),
    ("Basket Ball Orange",          "#F88158"),
    ("Coral",                       "#FF7F50"),
    ("Mango Tango",                 "#FF8243"),
    ("Salmon",                      "#FA8072"),
    ("Big Foot Feet",               "#E88E5A"),
    ("Tea Rose",                    "#F88379"),
    ("Royal Orange",                "#F99245"),
    ("Brown Sand",                  "#EE9A4D"),
    ("Sawtooth Oak",                "#EC956C"),
    ("Light Salmon Rose",           "#F9966B"),
    ("Atomic Tangerine",            "#FF9966"),
    ("Sandy Brown",                 "#F4A460"),
    ("Fawn",                        "#E5AA70"),
    ("Light Salmon",                "#FFA07A"),
    ("Rajah",                       "#FBAB60"),
    ("Very Light Tangelo",          "#FFB077"),
    ("Licorice",                    "#1A1110"),
    ("Chocolate Brown",             "#3F000F"),
    ("Root Beer",                   "#290E05"),
    ("Black Bean",                  "#3D0C02"),
    ("Zinnwaldite Brown",           "#2C1608"),
    ("Dark Scarlet",                "#560319"),
    ("Blood Red",                   "#660000"),
    ("Dark Sienna",                 "#3C1414"),
    ("Blood Night",                 "#551606"),
    ("Temptress",                   "#3C2126"),
    ("Barn Red",                    "#7C0A02"),
    ("Philippine Brown",            "#5D1916"),
    ("Plum Pie",                    "#7D0541"),
    ("Up Maroon",                   "#7B1113"),
    ("Light Chocolate Cosmos",      "#551F2F"),
    ("Seal Brown",                  "#59260B"),
    ("Dark Coffee",                 "#3B2F2F"),
    ("Oil",                         "#3B3131"),
    ("Prune",                       "#701C1C"),
    ("Old Burgundy",                "#43302E"),
    ("Kenyan Copper",               "#7C1C05"),
    ("Gray Brown",                  "#3D3635"),
    ("Claret",                      "#7F1734"),
    ("Black Cat",                   "#413839"),
    ("Bakers Brown",                "#5C3317"),
    ("Dark Lava",                   "#483C32"),
    ("Black Eel",                   "#463E3F"),
    ("Royal Brown",                 "#523B35"),
    ("Western Charcoal",            "#49413F"),
    ("Zinfandel Red",               "#5A3844"),
    ("Old Mauve",                   "#673147"),
    ("Philippine Bronze",           "#6E3A07"),
    ("Wine",                        "#722F37"),
    ("Garnet",                      "#733635"),
    ("Catawba",                     "#703642"),
    ("Sangria",                     "#7E3817"),
    ("Van Dyke Brown",              "#664228"),
    ("Kobicha",                     "#6B4423"),
    ("Velvet Maroon",               "#7E354D"),
    ("Roast Coffee",                "#704241"),
    ("Medium Tuscan Red",           "#79443B"),
    ("Medium Taupe",                "#674C47"),
    ("Umber",                       "#635147"),
    ("Coffee",                      "#6F4E37"),
    ("Tuscan Red",                  "#7C4848"),
    ("Wenge",                       "#645452"),
    ("Quincy",                      "#6A5445"),
    ("Mud",                         "#70543E"),
    ("Rosy Finch",                  "#7F4E52"),
    ("Zinc Gray",                   "#655B55"),
    ("Dull Purple",                 "#7F525D"),
    ("Deep Taupe",                  "#7E5E60"),
    ("Raw Umber",                   "#826644"),
    ("Gold Fusion",                 "#85754E"),
    ("Army Brown",                  "#827B60"),
    ("Shadow",                      "#8A795D"),
    ("Pale Brown",                  "#987654"),
    ("Toad",                        "#8B7D6B"),
    ("Dark Tan",                    "#918151"),
    ("Bullet Shell",                "#AF9B60"),
    ("Grullo",                      "#A99A86"),
    ("Lion",                        "#C19A6B"),
    ("Pale Oak",                    "#BBA46D"),
    ("White Oak",                   "#CE9F6F"),
    ("Light French Beige",          "#C8AD7F"),
    ("Ecru",                        "#C2B280"),
    ("Tan",                         "#D2B48C"),
    ("Burlywood",                   "#DEB887"),
    ("Dark Vanilla",                "#D1BEA8"),
    ("Deer Brown",                  "#E6BF83"),
    ("Pale Gold",                   "#E6BE8A"),
    ("Buff",                        "#F0DC82"),
    ("Bone",                        "#E3DAC9"),
    ("Mellow Yellow",               "#F8DE7E"),
    ("Sunset",                      "#FAD6A5"),
    ("Light Orange",                "#FED8B1"),
    ("Dutch White",                 "#EFDFBB"),
    ("Wheat",                       "#F5DEB3"),
    ("Pearl",                       "#EAE0C8"),
    ("Almond",                      "#EFDECD"),
    ("Dark Blonde",                 "#F0E2B6"),
    ("Navajo White",                "#FFDEAD"),
    ("Medium Champagne",            "#F3E5AB"),
    ("Golden Silk",                 "#F3E3C3"),
    ("Very Pale Orange",            "#FFDFBF"),
    ("Golden Blonde",               "#FBE7A1"),
    ("Banana Mania",                "#FAE7B5"),
    ("Peach",                       "#FFE5B4"),
    ("Bisque",                      "#FFE4C4"),
    ("Lemon Meringue",              "#F6EABE"),
    ("Parchment",                   "#F1E9D2"),
    ("Eggshell",                    "#F0EAD6"),
    ("Antique White",               "#FAEBD7"),
    ("Blanched Almond",             "#FFEBCD"),
    ("Papaya Whip",                 "#FFEFD5"),
    ("Soft Ivory",                  "#FAF0DD"),
    ("Cornsilk",                    "#FFF8DC"),
    ("Egg Shell",                   "#FFF9E3"),
    ("Dark Bronze",                 "#804A00"),
    ("Brown",                       "#964B00"),
    ("Windsor Tan",                 "#A75502"),
    ("Oak Brown",                   "#806517"),
    ("Coyote Brown",                "#81613C"),
    ("Golden Brown",                "#996515"),
    ("Sandy Taupe",                 "#967117"),
    ("Dark Bisque",                 "#B86500"),
    ("Hazel",                       "#8E7618"),
    ("Wood",                        "#966F33"),
    ("Sedona",                      "#CC6600"),
    ("Philippine Gold",             "#B17304"),
    ("Gold",                        "#A57C00"),
    ("Metallic Sunburst",           "#9C7C38"),
    ("Mustard Brown",               "#CD7A00"),
    ("Dark Goldenrod",              "#B8860B"),
    ("Golden Oak",                  "#BB8141"),
    ("Cinnamon",                    "#C58917"),
    ("Caramel",                     "#C68E17"),
    ("Fulvous",                     "#E48400"),
    ("Harvest Gold",                "#DA9100"),
    ("Tangerine",                   "#F28500"),
    ("Vivid Amber",                 "#CC9900"),
    ("Neon Tangerine",              "#F6890A"),
    ("Aztec Gold",                  "#C39953"),
    ("Cookie Brown",                "#C7A317"),
    ("Lemon Curry",                 "#CCA01D"),
    ("Dark Orange",                 "#FF8C00"),
    ("Carrot Orange",               "#ED9121"),
    ("Orange Gold",                 "#D4A017"),
    ("Princeton Orange",            "#FF8F00"),
    ("Gamboge",                     "#E49B0F"),
    ("Satin Sheen Gold",            "#CBA135"),
    ("Neon Gold",                   "#CFAA01"),
    ("Goldenrod",                   "#DAA520"),
    ("Vivid Gamboge",               "#FF9900"),
    ("Marigold",                    "#EAA221"),
    ("Mustard Yellow",              "#E1AD01"),
    ("Vivid Orange Peel",           "#FFA000"),
    ("Neon Carrot",                 "#FF9933"),
    ("Metallic Gold",               "#D3AF37"),
    ("Urobilin",                    "#E1AD21"),
    ("Bee Yellow",                  "#E9AB17"),
    ("Old Gold",                    "#CFB53B"),
    ("Indian Yellow",               "#E3A857"),
    ("Fall Leaf Brown",             "#C8B560"),
    ("Earth Yellow",                "#E1A95F"),
    ("Sunray",                      "#E3AB57"),
    ("Cantaloupe",                  "#FFA62F"),
    ("Traffic Yellow",              "#F7B500"),
    ("Beer",                        "#FBB117"),
    ("Spanish Yellow",              "#F6B511"),
    ("Xanthous",                    "#F1B42F"),
    ("Microsoft Yellow",            "#FDB900"),
    ("Deep Yellow",                 "#F6BE00"),
    ("Selective Yellow",            "#FFBA00"),
    ("Yellow Orange",               "#FFAE42"),
    ("Mango",                       "#FDBE02"),
    ("Lanzones",                    "#E0BC5B"),
    ("Orange-Yellow",               "#F5BD1F"),
    ("Middle Yellow Red",           "#ECB176"),
    ("Amber",                       "#FFBF00"),
    ("Golden Poppy",                "#FCC200"),
    ("Pastel Orange",               "#FFB347"),
    ("Maximum Yellow Red",          "#F2BA49"),
    ("Mikado Yellow",               "#FFC40C"),
    ("Deep Lemon",                  "#F5C71A"),
    ("Saffron",                     "#F4C430"),
    ("Macaroni and Cheese",         "#F2BB66"),
    ("Jonquil",                     "#F4CA16"),
    ("Ripe Mango",                  "#FFC324"),
    ("Philippine Yellow",           "#FECB00"),
    ("Mellow Apricot",              "#F8B878"),
    ("Tangerine Yellow",            "#FFCC00"),
    ("Metallic Yellow",             "#FDCC0D"),
    ("Zinc Yellow",                 "#FACA30"),
    ("Cyber Yellow",                "#FFD300"),
    ("Bright Gold",                 "#FDD017"),
    ("Sunglow",                     "#FFCC33"),
    ("Chrome Gold",                 "#FFCE44"),
    ("Topaz",                       "#FFC87C"),
    ("Stil De Grain Yellow",        "#FADA5E"),
    ("Mustard",                     "#FFDB58"),
    ("Shandy",                      "#FFE670"),
    ("Sun Yellow",                  "#FFE87C"),
    ("Black Chestnut Oak",          "#252321"),
    ("Olive Drab #7",               "#3C341F"),
    ("Café Noir",                   "#4B3621"),
    ("Pineapple",                   "#563C0D"),
    ("Violin Brown",                "#674403"),
    ("Dark Brown",                  "#654321"),
    ("Sepia",                       "#704214"),
    ("Field Drab",                  "#6C541E"),
    ("Red Dirt",                    "#7F5217"),
    ("Sandstone",                   "#786D5F"),
    ("Khaki Green",                 "#8A865D"),
    ("Olive Green",                 "#B5B35C"),
    ("Misty Moss",                  "#BBB477"),
    ("Dark Khaki",                  "#BDB76B"),
    ("Sage",                        "#BCB88A"),
    ("Flax",                        "#EEDC82"),
    ("Khaki",                       "#F0E68C"),
    ("Tan Brown",                   "#ECE5B6"),
    ("Dirty White",                 "#E8E4C9"),
    ("Pale Goldenrod",              "#EEE8AA"),
    ("Key Lime",                    "#E8F48C"),
    ("Pale Spring Bud",             "#ECEBBD"),
    ("Corn Yellow",                 "#FFF380"),
    ("Pastel Yellow",               "#FDFD96"),
    ("Beige",                       "#F5F5DC"),
    ("Canary",                      "#FFFF99"),
    ("Blonde",                      "#FBF6D9"),
    ("Light Goldenrod Yellow",      "#FAFAD2"),
    ("Lemon Chiffon",               "#FFFACD"),
    ("Very Pale Yellow",            "#FFFFBF"),
    ("Cream",                       "#FFFDD0"),
    ("Light Yellow",                "#FFFFE0"),
    ("Olive",                       "#808000"),
    ("Dark Moccasin",               "#827839"),
    ("Dark Yellow",                 "#8B8000"),
    ("Old Moss Green",              "#867E36"),
    ("Light Gold",                  "#B29700"),
    ("Citron",                      "#9FA91F"),
    ("Brass",                       "#B5A642"),
    ("Acid Green",                  "#B0BF1A"),
    ("Vegas Gold",                  "#C5B358"),
    ("Avocado Green",               "#B2C248"),
    ("Ginger Brown",                "#C9BE62"),
    ("Citrine",                     "#E4D00A"),
    ("Bitter Lemon",                "#CAE00D"),
    ("Safety Yellow",               "#EED202"),
    ("Pear",                        "#D1E231"),
    ("Peridot",                     "#E6E200"),
    ("School Bus Yellow",           "#FFD800"),
    ("Rubber Ducky Yellow",         "#FFD801"),
    ("Sizzling Sunrise",            "#FFDB00"),
    ("Neon Yellow Green",           "#DAEE01"),
    ("Titanium Yellow",             "#EEE600"),
    ("Bold Yellow",                 "#F9DB24"),
    ("Golden Yellow",               "#FFDF00"),
    ("Hansa Yellow",                "#E9D66B"),
    ("Straw",                       "#E4D96F"),
    ("Banana Yellow",               "#F5E216"),
    ("Maximum Green Yellow",        "#D9E650"),
    ("Vivid Yellow",                "#FFE302"),
    ("Booger Buster",               "#DDE26A"),
    ("Xanthic",                     "#EEED09"),
    ("Cardboard Brown",             "#EDDA74"),
    ("Minion Yellow",               "#F5E050"),
    ("Yellow Green Grosbeak",       "#E2F516"),
    ("Dandelion",                   "#DDF719"),
    ("Middle Yellow",               "#FFEB00"),
    ("Aureolin",                    "#FDEE00"),
    ("Canary Yellow",               "#FFEF00"),
    ("Yellow Rose",                 "#FFF000"),
    ("Lemon Lime",                  "#E3FF00"),
    ("Cadmium Yellow",              "#FFF600"),
    ("Yellow Sunshine",             "#FFF700"),
    ("Watermelon Yellow",           "#EEFF1B"),
    ("Maize",                       "#FBEC5D"),
    ("Lemon Glacier",               "#FDFF00"),
    ("Yellow",                      "#FFFF00"),
    ("Maximum Yellow",              "#FAFA37"),
    ("Lemon Yellow",                "#FFF44F"),
    ("Icterine",                    "#FCF75E"),
    ("Unmellow Yellow",             "#FFFF66"),
    ("Army Green",                  "#4B5320"),
    ("Antique Bronze",              "#665D1E"),
    ("Mustard Green",               "#6E6E30"),
    ("Middle Green",                "#4D8C57"),
    ("Dull Sea Green",              "#4E8975"),
    ("Fall Forest Green",           "#4E9258"),
    ("Smoke",                       "#738276"),
    ("Xanadu",                      "#738678"),
    ("Camouflage Green",            "#78866B"),
    ("Russian Green",               "#679267"),
    ("Sage Green",                  "#848B79"),
    ("Oxley",                       "#6D9A79"),
    ("Shiny Shamrock",              "#5FA778"),
    ("Asparagus",                   "#7BA05B"),
    ("Dinosaur Green",              "#73A16C"),
    ("Moss Green",                  "#8A9A5B"),
    ("Bud Green",                   "#7BB661"),
    ("Morning Blue",                "#8DA399"),
    ("Mantis",                      "#74C365"),
    ("Dollar Bill Green",           "#85BB65"),
    ("Iguana Green",                "#9CB071"),
    ("Olivine",                     "#9AB973"),
    ("Dark Sea Green",              "#8FBC8F"),
    ("Pistachio",                   "#93C572"),
    ("Middle Green Yellow",         "#ACBF60"),
    ("Laurel Green",                "#A9BA9D"),
    ("Frog Green",                  "#99C68E"),
    ("Pastel Green",                "#77DD77"),
    ("Eton Blue",                   "#96C8A2"),
    ("Cambridge Blue",              "#A3C1AD"),
    ("Turquoise Green",             "#A0D6B4"),
    ("Light Green",                 "#90EE90"),
    ("Teal Deer",                   "#99E6B3"),
    ("Granny Smith Apple",          "#A8E4A0"),
    ("Light Moss Green",            "#ADDFAD"),
    ("Celadon",                     "#ACE1AF"),
    ("Medium Spring Bud",           "#C9DC87"),
    ("Pale Green",                  "#98FB98"),
    ("Green Thumb",                 "#B5EAAA"),
    ("Mint Green",                  "#98FF98"),
    ("Magic Mint",                  "#AAF0D1"),
    ("Menthol",                     "#C1F9A2"),
    ("Tea Green",                   "#D0F0C0"),
    ("Light Jade",                  "#C3FDB8"),
    ("Mindaro",                     "#E3F988"),
    ("Organic Brown",               "#E3F9A6"),
    ("Light Rose Green",            "#DBF9DB"),
    ("Nyanza",                      "#E9FFDB"),
    ("Office Green",                "#008000"),
    ("Neon Dark Green",             "#008443"),
    ("Philippine Green",            "#008543"),
    ("India Green",                 "#138808"),
    ("Napier Green",                "#2A8000"),
    ("Traffic Green",               "#008754"),
    ("Spanish Green",               "#009150"),
    ("Forest Green",                "#228B22"),
    ("Slimy Green",                 "#299617"),
    ("Shamrock Green",              "#009E60"),
    ("Sea Foam Green",              "#2E8B57"),
    ("Green Frog",                  "#00A86B"),
    ("Dark Mint",                   "#31906E"),
    ("Parrot Green",                "#12AD2B"),
    ("Go Green",                    "#00AB66"),
    ("May Green",                   "#4C9141"),
    ("Maximum Green",               "#5E8C31"),
    ("Venom Green",                 "#728C00"),
    ("Vine Green",                  "#38A32A"),
    ("Dark Lime Green",             "#41A317"),
    ("Olive Drab",                  "#6B8E23"),
    ("Dark Pastel Green",           "#03C03C"),
    ("Green Pepper",                "#4AA02C"),
    ("Clover Green",                "#3EA055"),
    ("Earth Green",                 "#34A56F"),
    ("Vivid Malachite",             "#00CC33"),
    ("Green Onion",                 "#6AA121"),
    ("Kelly Green",                 "#4CBB17"),
    ("Medium Sea Green",            "#3CB371"),
    ("Mint",                        "#3EB489"),
    ("Green Apple",                 "#4CC417"),
    ("Malachite",                   "#0BDA51"),
    ("Lime Green",                  "#32CD32"),
    ("Microsoft Green",             "#7DB700"),
    ("Green Snake",                 "#6CBB3C"),
    ("Pea Green",                   "#52D017"),
    ("Lime",                        "#00FF00"),
    ("Alien Green",                 "#6CC417"),
    ("UFO Green",                   "#3CD070"),
    ("Zombie Green",                "#54C571"),
    ("Emerald",                     "#50C878"),
    ("Erin",                        "#00FF40"),
    ("Sgbus Green",                 "#55DD33"),
    ("Limerick",                    "#9DC209"),
    ("Android Green",               "#3DDC84"),
    ("Spring Green",                "#00FF7F"),
    ("Medium Spring Green",         "#00FA9A"),
    ("Nebula Green",                "#59E817"),
    ("Green Peas",                  "#89C35C"),
    ("Sheen Green",                 "#8FD400"),
    ("Harlequin",                   "#3FFF00"),
    ("Neon Green",                  "#39FF14"),
    ("Alien Armpit",                "#84DE02"),
    ("Medium Aqua Marine",          "#66CDAA"),
    ("Yellow-Green",                "#9ACD32"),
    ("Salad Green",                 "#A1C935"),
    ("Stoplight Go Green",          "#57E964"),
    ("Lime Mint Green",             "#36F57F"),
    ("Vivid Lime Green",            "#A6D608"),
    ("Hummingbird Green",           "#7FE817"),
    ("Emerald Green",               "#5FFB17"),
    ("Medium Aquamarine",           "#66DDAA"),
    ("Bright Green",                "#66FF00"),
    ("Light Malachite Green",       "#64E986"),
    ("Lawn Green",                  "#7CFC00"),
    ("Chartreuse",                  "#7FFF00"),
    ("Yellow Lawn Green",           "#87F717"),
    ("Jade Green",                  "#5EFB6E"),
    ("Aloe Vera Green",             "#98F516"),
    ("Screamin’ Green",             "#66FF66"),
    ("June Bud",                    "#BDDA57"),
    ("Mango Green",                 "#96FF00"),
    ("Spring Frost",                "#87FF2A"),
    ("Dragon Green",                "#6AFB92"),
    ("Spring Bud",                  "#A7FC00"),
    ("Green Lizard",                "#A7F432"),
    ("French Lime",                 "#9EFD38"),
    ("Inchworm",                    "#B2EC5D"),
    ("Slime Green",                 "#BCE954"),
    ("Chameleon Green",             "#BDF516"),
    ("Dull Green Yellow",           "#B1FB17"),
    ("Green-Yellow",                "#ADFF2F"),
    ("Electric Lime",               "#CCFF00"),
    ("Volt",                        "#CEFF00"),
    ("Aquamarine",                  "#7FFFD4"),
    ("Arctic Lime",                 "#D0FF14"),
    ("Dark Green",                  "#013220"),
    ("Sacramento State Green",      "#043927"),
    ("Phthalo Green",               "#123524"),
    ("British Racing Green",        "#004225"),
    ("Dark Forest Green",           "#254117"),
    ("Pakistan Green",              "#006600"),
    ("Kombu Green",                 "#354230"),
    ("Deep Emerald Green",          "#046307"),
    ("Lincoln Green",               "#195905"),
    ("Royal Green",                 "#136207"),
    ("Rifle Green",                 "#414833"),
    ("Cadmium Green",               "#006B3C"),
    ("Dartmouth Green",             "#00703C"),
    ("Mughal Green",                "#306030"),
    ("Metallic Green",              "#296E01"),
    ("Xbox Green",                  "#0E7A0D"),
    ("Hunter Green",                "#355E3B"),
    ("La Salle Green",              "#087830"),
    ("Medium Green",                "#037949"),
    ("Dark Moss Green",             "#4A5D23"),
    ("Dark Spring Green",           "#177245"),
    ("Deep Sea Green",              "#306754"),
    ("Feldgrau",                    "#4D5D53"),
    ("Salem",                       "#177B4D"),
    ("Medium Forest Green",         "#347235"),
    ("Ebony",                       "#555D50"),
    ("Dark Olive Green",            "#556B2F"),
    ("Artichoke Green",             "#4B6F44"),
    ("Seaweed Green",               "#437C17"),
    ("Amazon",                      "#3B7A57"),
    ("Sap Green",                   "#507D2A"),
    ("Fern Green",                  "#4F7942"),
    ("Hazel Green",                 "#617C58"),
    ("Wintergreen Dream",           "#56887D"),
    ("Steel Teal",                  "#5F8A8F"),
    ("Cadet Blue",                  "#5F9EA0"),
    ("Polished Pine",               "#5DA493"),
    ("Green Sheen",                 "#6EAEA1"),
    ("Blue Hosta",                  "#77BFC7"),
    ("Northern Lights Blue",        "#78C7C7"),
    ("Blue Green",                  "#7BCCB5"),
    ("Cyan Opaque",                 "#92C7C7"),
    ("Opal",                        "#A8C3BC"),
    ("Tiffany Blue",                "#81D8D0"),
    ("Pearl Aqua",                  "#88D8C0"),
    ("Middle Blue Green",           "#8DD9CC"),
    ("Medium Sky Blue",             "#80DAEB"),
    ("Pale Robin Egg Blue",         "#96DED1"),
    ("Blue Lagoon",                 "#8EEBEC"),
    ("Powder Blue",                 "#B0E0E6"),
    ("Pale Blue",                   "#AFEEEE"),
    ("Light Aquamarine",            "#93FFE8"),
    ("Waterspout",                  "#A4F4F9"),
    ("Pale Blue Lily",              "#CFECEC"),
    ("Italian Sky Blue",            "#B2FFFF"),
    ("Light Slate",                 "#CCFFFF"),
    ("Light Cyan",                  "#E0FFFF"),
    ("Teal",                        "#008080"),
    ("Teal Green",                  "#00827F"),
    ("Metallic Seaweed",            "#0A7E8C"),
    ("Zircon Blue",                 "#00849D"),
    ("Dark Cyan",                   "#008B8B"),
    ("Green-Cyan",                  "#009966"),
    ("Paolo Veronese Green",        "#009B7D"),
    ("Viridian Green",              "#009698"),
    ("Viridian",                    "#40826D"),
    ("Aquamarine Stone",            "#348781"),
    ("Illuminating Emerald",        "#319177"),
    ("Persian Green",               "#00A693"),
    ("Sea Turtle Green",            "#438D80"),
    ("Deep Sea",                    "#3B9C9C"),
    ("Jungle Green",                "#29AB87"),
    ("Zomp",                        "#39A78E"),
    ("Light Sea Green",             "#20B2AA"),
    ("Seafoam Green",               "#3EA99F"),
    ("Caribbean Green",             "#00CC99"),
    ("Keppel",                      "#3AB09E"),
    ("Mountain Meadow",             "#30BA8F"),
    ("Robin Egg Blue",              "#00CCCC"),
    ("Dark Turquoise",              "#00CED1"),
    ("Verdigris",                   "#43B3AE"),
    ("Maximum Blue Green",          "#30BFBF"),
    ("Macaw Blue Green",            "#43BFC7"),
    ("Jellyfish",                   "#46C7C7"),
    ("Blue Turquoise",              "#43C6DB"),
    ("Bright Turquoise",            "#08E8DE"),
    ("Deep Turquoise",              "#48CCCD"),
    ("Eucalyptus",                  "#44D7A8"),
    ("Medium Turquoise",            "#48D1CC"),
    ("Technobotanica",              "#00FFBF"),
    ("Olo",                         "#01FFCD"),
    ("Turquoise",                   "#40E0D0"),
    ("Fluorescent Blue",            "#15F4EE"),
    ("Turquoise Blue",              "#00FFEF"),
    ("Lotion Blue",                 "#15F2FD"),
    ("Neon Cyan",                   "#00FEFC"),
    ("Cyan",                        "#00FFFF"),
    ("Bright Cyan",                 "#0AFFFF"),
    ("Blue Diamond",                "#4EE2EC"),
    ("Blue Zircon",                 "#57FEFF"),
    ("Electric Blue",               "#7DF9FF"),
    ("Tron Blue",                   "#7DFDFE"),
    ("Dark Jungle Green",           "#1A2421"),
    ("Charleston Green",            "#232B2B"),
    ("Deep Teal",                   "#033E3E"),
    ("Medium Jungle Green",         "#1C352D"),
    ("Warm Black",                  "#004242"),
    ("Deep Jungle Green",           "#004B49"),
    ("Msu Green",                   "#18453B"),
    ("Japanese Indigo",             "#264348"),
    ("Medium Teal",                 "#045F5F"),
    ("Dark Slate Gray",             "#2F4F4F"),
    ("Blue Moss Green",             "#3C565B"),
    ("Tropical Rain Forest",        "#00755E"),
    ("Skobeloff",                   "#007474"),
    ("Pine Green",                  "#01796F"),
    ("Spanish Viridian",            "#007F5C"),
    ("Generic Viridian",            "#007F66"),
    ("Myrtle Green",                "#317873"),
    ("Ming",                        "#36747D"),
    ("Greenish Blue",               "#307D7E"),
    ("Hooker’s Green",              "#49796B"),
    ("Beetle Green",                "#4C787E"),
    ("Grayish Turquoise",           "#5E7D7E"),
    ("Purple Navy",                 "#4E5180"),
    ("Dark Blue-Gray",              "#666699"),
    ("Very Peri",                   "#6667AB"),
    ("Slate Granite Gray",          "#657383"),
    ("Rat Gray",                    "#6D7B8D"),
    ("Rhythm",                      "#777696"),
    ("Slate Gray",                  "#708090"),
    ("Slate Blue Grey",             "#737CA1"),
    ("Glaucous",                    "#6082B6"),
    ("Periwinkle Purple",           "#7575CF"),
    ("Rackley",                     "#5D8AA8"),
    ("Light Slate Grey",            "#778899"),
    ("Shadow Blue",                 "#778BA5"),
    ("Roman Silver",                "#838996"),
    ("Light Purple Blue",           "#728FCE"),
    ("Blue Koi",                    "#659EC7"),
    ("Cerulean Frost",              "#6D9BC3"),
    ("Cool Gray",                   "#8C92AC"),
    ("Air Superiority Blue",        "#72A0C1"),
    ("Vista Blue",                  "#7C9ED9"),
    ("Manatee",                     "#979AAA"),
    ("Iceberg",                     "#71A6D2"),
    ("Moonstone Blue",              "#73A9C2"),
    ("Cadet Gray",                  "#91A3B0"),
    ("Pewter Blue",                 "#8BA8B7"),
    ("Light Cobalt Blue",           "#88ACE0"),
    ("Blue Bell",                   "#A2A2D0"),
    ("Blue Gray",                   "#98AFC7"),
    ("Wild Blue Yonder",            "#A2ADD0"),
    ("Dark Sky Blue",               "#8CBED6"),
    ("Maximum Blue Purple",         "#ACACE6"),
    ("Carolina Blue",               "#99BADD"),
    ("Day Sky Blue",                "#82CAFF"),
    ("Pale Cerulean",               "#9BC4E2"),
    ("Sky Blue",                    "#87CEEB"),
    ("Middle Blue",                 "#7ED4E6"),
    ("Light Sky Blue",              "#87CEFA"),
    ("Baby Blue",                   "#89CFF0"),
    ("Light Cornflower Blue",       "#93CCEA"),
    ("Pastel Blue",                 "#AEC6CF"),
    ("Pale Cyan",                   "#87D3F8"),
    ("Baby Blue Eyes",              "#A1CAF1"),
    ("Jeans Blue",                  "#A0CFEC"),
    ("Pale Cornflower Blue",        "#ABCDEF"),
    ("Light Steel Blue",            "#B0CFDE"),
    ("Blue Angel",                  "#B7CEEC"),
    ("Light Periwinkle",            "#C5CBE1"),
    ("Light Blue",                  "#ADD8E6"),
    ("Columbia Blue",               "#9BDDFF"),
    ("Non-Photo Blue",              "#A4DDED"),
    ("Soap",                        "#CEC8EF"),
    ("Pale Aqua",                   "#BCD4E6"),
    ("Coral Blue",                  "#AFDCEC"),
    ("Lavender Blue",               "#CCCCFF"),
    ("Light Day Blue",              "#ADDFFF"),
    ("Gulf Blue",                   "#C9DFEC"),
    ("Heavenly Blue",               "#C6DEFF"),
    ("Water",                       "#D4F1F9"),
    ("Navy Blue",                   "#000080"),
    ("Dark Blue",                   "#00008B"),
    ("Duke Blue",                   "#00009C"),
    ("New Midnight Blue",           "#0000A0"),
    ("Earth Blue",                  "#0000A5"),
    ("Medium Blue",                 "#0000CD"),
    ("Phthalo Blue",                "#000F89"),
    ("Neon Blue",                   "#1B03A3"),
    ("Blue",                        "#0000FF"),
    ("Blue Ribbon",                 "#0B10A2"),
    ("Resolution Blue",             "#002387"),
    ("Bright Blue",                 "#0909FF"),
    ("Imperial Blue",               "#002395"),
    ("Denim Dark Blue",             "#151B8D"),
    ("Samsung Blue",                "#12279E"),
    ("Philippine Blue",             "#0038A7"),
    ("Royal Azure",                 "#0038A8"),
    ("Canary Blue",                 "#2916F5"),
    ("Egyptian Blue",               "#1034A6"),
    ("Cosmic Cobalt",               "#2E2D88"),
    ("Blueberry Blue",              "#0041C2"),
    ("Cobalt Blue",                 "#0047AB"),
    ("Persian Blue",                "#1C39BB"),
    ("Absolute Zero",               "#0048BA"),
    ("Medium Electric Blue",        "#035096"),
    ("Yale Blue",                   "#0F4D92"),
    ("Traffic Blue",                "#0E518D"),
    ("Denim Blue",                  "#2243B6"),
    ("Iridescent Indigo",           "#3C32CD"),
    ("Iron Indigo",                 "#184FA1"),
    ("Palatinate Blue",             "#273BE2"),
    ("Dark Slate Blue",             "#483D8B"),
    ("Sapphire",                    "#0F52BA"),
    ("Blue Sapphire",               "#126180"),
    ("Yinmn Blue",                  "#2E5090"),
    ("Blue Orchid",                 "#1F45FC"),
    ("Sea Blue",                    "#006994"),
    ("Violet-Blue",                 "#324AB2"),
    ("New Car",                     "#214FC6"),
    ("Medium Persian Blue",         "#0067A5"),
    ("B’Dazzled Blue",              "#2E5894"),
    ("Cerulean Blue",               "#2A52BE"),
    ("Honolulu Blue",               "#006DB0"),
    ("Denim",                       "#1560BD"),
    ("Green-Blue",                  "#1164B4"),
    ("Lapis Lazuli",                "#26619C"),
    ("Spanish Blue",                "#0070B8"),
    ("French Blue",                 "#0072BB"),
    ("Philippine Sky Blue",         "#0066FF"),
    ("Blue Eyes",                   "#1569C7"),
    ("True Blue",                   "#0073CF"),
    ("Cerulean",                    "#007BA7"),
    ("Ocean Boat Blue",             "#0077BE"),
    ("Deep Periwinkle",             "#5453A6"),
    ("Star Command Blue",           "#007BB8"),
    ("Balloon Blue",                "#2B60DE"),
    ("Microsoft Edge Blue",         "#0078D7"),
    ("Iris",                        "#5A4FCF"),
    ("Azure Blue",                  "#4863A0"),
    ("Ocean Blue",                  "#2B65EC"),
    ("Bright Navy Blue",            "#1974D2"),
    ("Queen Blue",                  "#436B95"),
    ("Teal Blue",                   "#367588"),
    ("Majorelle Blue",              "#6050DC"),
    ("Savoy Blue",                  "#4B61D1"),
    ("Azure",                       "#007FFF"),
    ("Bluetiful",                   "#3C69E7"),
    ("Blue Dress",                  "#157DEC"),
    ("Royal Blue",                  "#4169E1"),
    ("Ultramarine Blue",            "#4166F5"),
    ("Han Blue",                    "#446CCF"),
    ("Slate Blue",                  "#6A5ACD"),
    ("Blue Yonder",                 "#5072A7"),
    ("Rich Electric Blue",          "#0892D0"),
    ("Windows Blue",                "#357EC7"),
    ("Blue-Green",                  "#0D98BA"),
    ("Blue Lotus",                  "#6960EC"),
    ("Tufts Blue",                  "#417DC1"),
    ("Indigo",                      "#6A5DFF"),
    ("Steel Blue",                  "#4682B4"),
    ("Very Light Blue",             "#6666FF"),
    ("Glacial Blue Ice",            "#368BC1"),
    ("Vantg Blue",                  "#5271FF"),
    ("Blue Ivy",                    "#3090C7"),
    ("Microsoft Blue",              "#00A2ED"),
    ("Dodger Blue",                 "#1E90FF"),
    ("Bleu De France",              "#318CE7"),
    ("Medium Slate Blue",           "#7B68EE"),
    ("Silk Blue",                   "#488AC7"),
    ("Light Slate Blue",            "#736AFF"),
    ("Vivid Cerulean",              "#00AAEE"),
    ("Silver Lake Blue",            "#5D89BA"),
    ("Blueberry",                   "#4F86F7"),
    ("Pacific Blue",                "#1CA9C9"),
    ("Twitter Blue",                "#26A7DE"),
    ("Aero",                        "#00B9E8"),
    ("Moonstone",                   "#3AA8C1"),
    ("United Nations Blue",         "#5B92E5"),
    ("Deep Sky Blue",               "#00BFFF"),
    ("Livid",                       "#6699CC"),
    ("Cornflower Blue",             "#6495ED"),
    ("Butterfly Blue",              "#38ACEC"),
    ("Maximum Blue",                "#47ABCC"),
    ("Sky Blue Dress",              "#6698FF"),
    ("Vivid Sky Blue",              "#00CCFF"),
    ("Picton Blue",                 "#45B1E8"),
    ("Little Boy Blue",             "#6CA0DC"),
    ("Midday Blue",                 "#3BB9FF"),
    ("Blue Jeans",                  "#5DADEC"),
    ("Crystal Blue",                "#5CB3FF"),
    ("Blizzard Blue",               "#50BFE6"),
    ("French Sky Blue",             "#77B5FE"),
    ("Very Light Azure",            "#74BBFB"),
    ("Maya Blue",                   "#73C2FB"),
    ("Maastricht Blue",             "#001C3D"),
    ("Elderberry",                  "#17182B"),
    ("Oxford Blue",                 "#002147"),
    ("Night Blue",                  "#151B54"),
    ("Midnight Blue",               "#191970"),
    ("Prussian Blue",               "#003153"),
    ("Dark Midnight Blue",          "#003366"),
    ("Space Cadet",                 "#1D2951"),
    ("Traffic Black",               "#2A2D2F"),
    ("Deep Sea Blue",               "#123456"),
    ("St. Patrick’s Blue",          "#23297A"),
    ("Lapis Blue",                  "#15317E"),
    ("Gunmetal",                    "#2A3439"),
    ("Philippine Indigo",           "#00416A"),
    ("Dark Slate Grey",             "#25383C"),
    ("Dark Slate",                  "#2B3856"),
    ("Blue Whale",                  "#342D7E"),
    ("Dark Blue Grey",              "#29465B"),
    ("Charcoal",                    "#36454F"),
    ("Outer Space",                 "#414A4C"),
    ("Police Blue",                 "#374F6B"),
    ("Blue Jay",                    "#2B547E"),
    ("Metallic Blue",               "#32527B"),
    ("Independence",                "#4C516D"),
    ("Iron Gray",                   "#555D61"),
    ("Deep Space Sparkle",          "#4A646C"),
    ("Black Coral",                 "#54626F"),
    ("Cadet",                       "#536872"),
    ("Payne’s Gray",                "#536878"),
    ("Marble Blue",                 "#566D7E"),
    ("Jet Gray",                    "#616D7E"),
    ("Mist Blue",                   "#646D7E"),
    ("French Lilac",                "#86608E"),
    ("Middle Blue Purple",          "#8B72BE"),
    ("Ube",                         "#8878C3"),
    ("Medium Purple",               "#9370DB"),
    ("Purple Mountain Majesty",     "#9678B6"),
    ("Rich Lavender",               "#A76BCF"),
    ("Lavender Purple",             "#967BB6"),
    ("African Violet",              "#B284BE"),
    ("Glossy Grape",                "#AB92B3"),
    ("Light Pastel Purple",         "#B19CD9"),
    ("Bright Lilac",                "#D891EF"),
    ("Wisteria",                    "#C9A0DC"),
    ("Pale Violet",                 "#CC99FF"),
    ("Tropical Violet",             "#CDA4DE"),
    ("Mauve",                       "#E0B0FF"),
    ("Pale Lavender",               "#DCD0FF"),
    ("Websafe Indigo",              "#330099"),
    ("Ultramarine",                 "#3F00FF"),
    ("Metallic Violet",             "#5B0A91"),
    ("Purple",                      "#6A0DAD"),
    ("Spanish Violet",              "#4C2882"),
    ("Electric Indigo",             "#6F00FF"),
    ("Ksu Purple",                  "#512888"),
    ("Han Purple",                  "#5218FA"),
    ("Near Violet",                 "#8000FF"),
    ("Poison Purple",               "#7F01FE"),
    ("French Violet",               "#8806CE"),
    ("Dark Violet",                 "#9400D3"),
    ("Violet",                      "#8F00FF"),
    ("Eminence",                    "#6C3082"),
    ("Vivid Violet",                "#9F00FF"),
    ("Rebecca Purple",              "#663399"),
    ("Grape",                       "#6F2DA8"),
    ("Maximum Purple",              "#733380"),
    ("Vibrant Purple",              "#AA00FF"),
    ("Purple Heart",                "#69359C"),
    ("Purple Amethyst",             "#6C2DC7"),
    ("True Purple",                 "#BF00FF"),
    ("Vivid Mulberry",              "#B80CE3"),
    ("Plump Purple",                "#5946B2"),
    ("Clematis Violet",             "#842DCE"),
    ("Vivid Orchid",                "#CC00FF"),
    ("Blue-Violet",                 "#8A2BE2"),
    ("Veronica",                    "#A020F0"),
    ("Lovely Purple",               "#7F38EC"),
    ("Purple Violet",               "#8D38C9"),
    ("Dark Orchid",                 "#9932CC"),
    ("Royal Purple",                "#7851A9"),
    ("Aztech Purple",               "#893BFF"),
    ("Jasmine Purple",              "#A23BEC"),
    ("Purpureus",                   "#9A4EAE"),
    ("Purple Sage Bush",            "#7A5DC7"),
    ("Purple Plum",                 "#9C51B6"),
    ("Purple Flower",               "#A74AC7"),
    ("Purple Daffodil",             "#B041FF"),
    ("Navy Purple",                 "#9457EB"),
    ("Light Purple",                "#8467D7"),
    ("Amethyst",                    "#9966CC"),
    ("Medium Orchid",               "#BA55D3"),
    ("Crocus Purple",               "#9172EC"),
    ("Rich Lilac",                  "#B666D2"),
    ("Purple Mimosa",               "#9E7BFF"),
    ("Heliotrope Purple",           "#D462FF"),
    ("Heliotrope",                  "#DF73FF"),
    ("Petunia",                     "#470659"),
    ("Russian Violet",              "#32174D"),
    ("Persian Indigo",              "#32127A"),
    ("Purple Monster",              "#461B7E"),
    ("Purple Iris",                 "#571B7E"),
    ("Imperial",                    "#602F6B"),
    ("Purple Jam",                  "#6A287E"),
    ("Purple Haze",                 "#4E387E"),
    ("Old Heliotrope",              "#563C5C"),
    ("Cyber Grape",                 "#58427C"),
    ("Twilight Lavender",           "#8A496B"),
    ("Sugar Plum",                  "#914E75"),
    ("Razzmic Berry",               "#8D4E85"),
    ("Chinese Violet",              "#856088"),
    ("Antique Fuchsia",             "#915C83"),
    ("Mountbatten Pink",            "#997A8D"),
    ("Pearly Purple",               "#B768A2"),
    ("Super Pink",                  "#CF6BA9"),
    ("Sky Magenta",                 "#CF71AF"),
    ("Opera Mauve",                 "#B784A7"),
    ("French Mauve",                "#D473D4"),
    ("Orchid",                      "#DA70D6"),
    ("Heliotrope Gray",             "#AA98A9"),
    ("Lilac Luster",                "#AE98AA"),
    ("Middle Purple",               "#D982B5"),
    ("Purple Dragon",               "#C38EC7"),
    ("Pastel Purple",               "#B39EB5"),
    ("Persian Pink",                "#F77FBE"),
    ("Pastel Violet",               "#CB99C9"),
    ("Light Grayish Magenta",       "#CC99CC"),
    ("Lavender Magenta",            "#EE82EE"),
    ("Light Medium Orchid",         "#D39BCB"),
    ("Lilac",                       "#C8A2C8"),
    ("Pale Magenta",                "#F984E5"),
    ("Light Fuchsia Pink",          "#F984EF"),
    ("Wisteria Purple",             "#C6AEC7"),
    ("Kobi",                        "#E79FC4"),
    ("Medium Lavender Magenta",     "#DDA0DD"),
    ("Light Orchid",                "#E6A8D7"),
    ("Pink Pearl",                  "#E7ACCF"),
    ("Lavender Rose",               "#FBA0E3"),
    ("Blush Pink",                  "#E6A9EC"),
    ("Purple Thistle",              "#D2B9D3"),
    ("Maximum Pink",                "#F6A5F2"),
    ("Rich Brilliant Lavender",     "#F1A7FE"),
    ("Thistle",                     "#D8BFD8"),
    ("Blossom Pink",                "#F9B7FF"),
    ("Periwinkle Pink",             "#E9CFEC"),
    ("Shampoo",                     "#FFCFF1"),
    ("Pink Lace",                   "#FFDDF4"),
    ("Patriarch",                   "#800080"),
    ("Philippine Violet",           "#81007F"),
    ("Mardi Gras",                  "#880085"),
    ("Dark Magenta",                "#8B008B"),
    ("Flirt",                       "#A2006D"),
    ("Mauveine",                    "#8D029B"),
    ("Dark Fuchsia",                "#A00955"),
    ("Jazzberry Jam",               "#A50B5E"),
    ("Dark Raspberry",              "#872657"),
    ("Traffic Purple",              "#992572"),
    ("Maximum Violet",              "#892F77"),
    ("Mexican Pink",                "#E4007C"),
    ("Amaranth Deep Purple",        "#9F2B68"),
    ("Medium Violet-Red",           "#C71585"),
    ("Artist’s Purple",             "#C71585"),
    ("Hollywood Cerise",            "#F400A1"),
    ("Dark Carnation Pink",         "#C12283"),
    ("Berry Parfait",               "#A43482"),
    ("Psychedelic Purple",          "#DF00FF"),
    ("Vivid Cerise",                "#DA1D81"),
    ("Maximum Red Purple",          "#A63A79"),
    ("Plum",                        "#8E4585"),
    ("Hot Fuchsia",                 "#FF00C6"),
    ("Fandango",                    "#B53389"),
    ("Medium Red-Violet",           "#BB3385"),
    ("Barbie Pink",                 "#E0218A"),
    ("Royal Fuchsia",               "#CA2C92"),
    ("Deep Pink",                   "#FF1493"),
    ("Mystic Maroon",               "#AD4379"),
    ("Byzantine",                   "#BD33A4"),
    ("Fuchsia",                     "#FF00FF"),
    ("Shocking Pink",               "#FC0FC0"),
    ("Philippine Pink",             "#FA1A8E"),
    ("Pink Plum",                   "#B93B8F"),
    ("Deep Cerise",                 "#DA3287"),
    ("Steel Pink",                  "#CC33CC"),
    ("Dimorphotheca Magenta",       "#E3319D"),
    ("Orchid Purple",               "#B048B5"),
    ("Hot Magenta",                 "#FF1DCE"),
    ("Persian Rose",                "#FE28A2"),
    ("Mulberry",                    "#C54B8C"),
    ("Royal Pink",                  "#E73895"),
    ("Frostbite",                   "#E936A7"),
    ("Neon Hot Pink",               "#FD349C"),
    ("Crimson Purple",              "#E238EC"),
    ("Deep Fuchsia",                "#C154C1"),
    ("Razzle Dazzle Rose",          "#FF33CC"),
    ("Bright Neon Pink",            "#F433FF"),
    ("Wild Strawberry",             "#FF43A4"),
    ("Purple Pizzazz",              "#FE4EDA"),
    ("Brilliant Rose",              "#E667CE"),
    ("Ultra Pink",                  "#FF6FFF"),
    ("Pink Flamingo",               "#FC74FD"),
    ("Deep Purple",                 "#36013F"),
    ("Dark Purple",                 "#301934"),
    ("Purple Lily",                 "#550A35"),
    ("Tyrian Purple",               "#66023C"),
    ("Spanish Purple",              "#66033C"),
    ("Zinzolin",                    "#6C0277"),
    ("Plum Velvet",                 "#7D0552"),
    ("Pansy Purple",                "#78184A"),
    ("Palatinate Purple",           "#682860"),
    ("Japanese Violet",             "#5B3256"),
    ("Midnight",                    "#702670"),
    ("Plum Purple",                 "#583759"),
    ("Byzantium",                   "#702963"),
    ("Medium Violet",               "#65315F"),
    ("Purple Taupe",                "#50404D"),
    ("Dark Byzantium",              "#5D3954"),
    ("Quartz",                      "#51484F"),
    ("Eggplant",                    "#614051"),
    ("Viola Purple",                "#7E587E"),
    ("Old Lavender",                "#796878"),
];
