[package]
name = "ee-conio-engine"
version = "0.1.0-alpha.3"
edition = "2024"
description="ANSI escape sequence helpers (escape primitives, no dependencies)"
repository = "https://github.com/ErnieE5/ee-conio"
license = "MIT OR Apache-2.0"
include = ["/src","/tests"]

[lints.rust]
unsafe_code = "forbid"

[dependencies]
